### ISSUE TITLE
Вопросы по скетчу....

### ISSUE THREAD

**Issue by conrad66** [dodther/Energomonitor#1]
1. Переменные
byte TimeAdresseD = 9; 
byte TimeAdresseN = 11;
ни где не используются, хотя вроде бы завлено кооретирование времени в блинке.
2. Где в скетче активная мощьность какой принцип расчета  реактивной мощьности ?
3. Скечь точно работоспособный ??? 
Чем больше вникаю, тем больше складывается впечатление что скетч сильно порезан.....

**Comment by dodther** [comment]
1. Не используются так как я не дописал их использование. Это адреса в памяти где должны храниться значения перехода день и ночь на случай выключения питания.
2. Активную мощность выдаёт датчик в ваттах, Реактивная мощность считается в функции ReactivePower. Считается она умножением силы тока на напряжение, получаем полную мощность и из неё вычитаем активную. Но я не совсем уверен что так правильно.
3. Да, рабочий. Работает у меня на доме. Единственно забыл указать что загрузчик на нано надо сменить на оптибут, с родным не хватает места.

**Comment by dodther** [comment]
> 
> 
>     1. Переменные
>        byte TimeAdresseD = 9;
>        byte TimeAdresseN = 11;
>        ни где не используются, хотя вроде бы завлено кооретирование времени в блинке.
> 
>     2. Где в скетче активная мощьность какой принцип расчета  реактивной мощьности ?
> 
>     3. Скечь точно работоспособный ???
>        Чем больше вникаю, тем больше складывается впечатление что скетч сильно порезан.....

1. Не используются так как я не дописал их использование. Это адреса в памяти где должны храниться значения перехода день и ночь на случай выключения питания.
2. Активную мощность выдаёт датчик в ваттах, Реактивная мощность считается в функции ReactivePower. Считается она умножением силы тока на напряжение, получаем полную мощность и из неё вычитаем активную. Но я не совсем уверен что так правильно.
3. Да, рабочий. Работает у меня на доме. Единственно забыл указать что загрузчик на нано надо сменить на оптибут, с родным не хватает места.

**Comment by conrad66** [comment]
По поводу переменных понял, спасибо.
Есть еще несколько вопросов по скетчу, если позволите....
1. Что за порты в переменной ports[3][5], что значат те цифры в массивах?
2. vipe[3][4]; это три фазы по 4 получаемых значения с pzem ? я правильно понял ?
3. Что происходит при пропадании питания ?  и что даст хранение значений перехода день/ночь ?
4. Вы каждый раз в при переходе день - ночь выставляете флаг ResetWh = 1; тем самым обнуляя при переходе показание kWh в PZEN, я правильно понял ?
Можно как то обойти это если нет физической возможности  (транзисторы +оптопара ) обнулять показание  ? 
p.s. уточните пожалуйста марку транзисторов которые Вы использовали, номинал второго резистора если оптопара, например, 817

**Comment by conrad66** [comment]
5. Почему были выбраны 18 и 19 пины для сброса ? Они обязательно должны быть аналоговыми ?

**Comment by conrad66** [comment]
Надо ли при первоночальном запуске скетча пины 18,19
выставлять в LOW ?
 digitalWrite(18, LOW);
 digitalWrite(19, LOW); 
Или они по умочанию при включении arduino в LOW ?
При выставлении в HIGH, какой уровень на пинах 3.3в или 5в ?
Если использовать не ардуино, а например ESP8266, там вроде уровни 3.3в, такая схема будет работать ?

**Comment by conrad66** [comment]
И еще вопрос ... а на обном MOSFET это нельзя было реализовать ?

**Comment by dodther** [comment]
> 
> 
> По поводу переменных понял, спасибо.
> Есть еще несколько вопросов по скетчу, если позволите....
> 
>     1. Что за порты в переменной ports[3][5], что значат те цифры в массивах?
> 
>     2. vipe[3][4]; это три фазы по 4 получаемых значения с pzem ? я правильно понял ?
> 
>     3. Что происходит при пропадании питания ?  и что даст хранение значений перехода день/ночь ?
> 
>     4. Вы каждый раз в при переходе день - ночь выставляете флаг ResetWh = 1; тем самым обнуляя при переходе показание kWh в PZEN, я правильно понял ?
>        Можно как то обойти это если нет физической возможности  (транзисторы +оптопара ) обнулять показание  ?
>        p.s. уточните пожалуйста марку транзисторов которые Вы использовали, номинал второго резистора если оптопара, например, 817

1. Это массив виртуальных пинов  в блинке. Так как опрос 3 датчиков идет в переборе массива, то и пины записал в массив и там-же при переборе отправляю данные в блинк.
2. Правильно.
3. При пропадании питания, естественно, всё выключается. В данный момент переход день\ночь берётся из блинка, если после восстановления питания интернета нет, то хранение этих значений позволит корректно делать переход день\ночь.
4. Верно. Сброс показаний возможен только нажатием кнопки. Других способов сброса нет. Можно в коде запоминать сколько уже насчтинано и пересчитывать. Но это надо переписывать код. Оптопара обычная 817 с дохлых БП. Транзисторы обычные полевики N и P. Из них собран инвертор сигнала. Дело в том что для обнуления показаний UART должен быть обесточен. Но если 5в подавать напрямик с ноги ардуины то впри подаче питания порт запитывается слишком поздно и не работает. А при инверторе 5В есть всегда и для их прерывания надо подать высокий уровень на инвертор.

> 
> 
>     1. Почему были выбраны 18 и 19 пины для сброса ? Они обязательно должны быть аналоговыми ?

Пины могут быть любыми. Ведь там только поднимаем и опускаем сигнал. Это может делать любая нога наны.



> 
> 
> Надо ли при первоночальном запуске скетча пины 18,19
> выставлять в LOW ?
> digitalWrite(18, LOW);
> digitalWrite(19, LOW);
> Или они по умочанию при включении arduino в LOW ?
> При выставлении в HIGH, какой уровень на пинах 3.3в или 5в ?
> Если использовать не ардуино, а например ESP8266, там вроде уровни 3.3в, такая схема будет работать ?

По умолчанию в низком. Естественно 5В, ведь это 5 вольтовая нана. Должна.



> 
> 
> И еще вопрос ... а на обном MOSFET это нельзя было реализовать ?

Это инвертор, нужно 2 транзистора. У мена были NDC7001, я их использовал. Но ничего не мешает использовать 2 отдельных транзистора.

**Comment by conrad66** [comment]
спасибо, понял.
Какое сопротивление перед оптопарой ?

**Comment by dodther** [comment]
> 
> 
> спасибо, понял.
> Какое сопротивление перед оптопарой ?

Не помню. Вроде 4кОм. Можешь воспользоваться калькулятором для светодиодов.

**Comment by conrad66** [comment]
В функции void firstRun(byte DD) есть такие строчки :
EEPROM.put(TarrifAdresseD , int(0));
EEPROM.put(TarrifAdresseN  , int(0));
И они не закомментированы.
А перменные TarrifAdresseD  и TarrifAdresseN   ни где не описаны.
Компиляция скетча с ошибкой.
На гитхабе точно рабочий скетч ? :)

**Comment by conrad66** [comment]
И еще у меня вопросы.....
вот запустили ардуину или в первый раз или после пропадания питания..
Начал выполнятся 
void setup() 
Эти строчки понятно что делают :
DN = EEPROM.read(DNAdresse); 
  firstRun(DN);
  kWhDayAllERROM = EEPROM.get(dAdresse, kWhDayAllERROM);
  kWhNightAllERROM = EEPROM.get(nAdresse,kWhNightAllERROM);  
Вот по этим фунциям, есть вопросы..... 
  kWhNightUpdate();
  kWhDayUpdate();

Допустим рассмотрм void kWhDayUpdate()
строчки вызывают сомнение :
  uint32_t kWhDay = (vipe[0][3] + vipe[1][3] + vipe[2][3]);
  kWhDayAll=kWhDayAllERROM+kWhDay;
Массив  vipe определен, но он ничем не  заполнен, не понятно какие там значения.
Он начинает заполнятся только при вызове функции readEnergy();, а ее еще не вызывали, она в void loop().

Что я не понимаю ????

**Comment by dodther** [comment]
> 
> 
> В функции void firstRun(byte DD) есть такие строчки :
> EEPROM.put(TarrifAdresseD , int(0));
> EEPROM.put(TarrifAdresseN , int(0));
> И они не закомментированы.
> А перменные TarrifAdresseD и TarrifAdresseN ни где не описаны.
> Компиляция скетча с ошибкой.
> На гитхабе точно рабочий скетч ? :)

В смысле нигде не описаны? А что тогда в в 22 и 23 строках?
А где текст ошибки?
Рабочий.



> 
> 
> И еще у меня вопросы.....
> вот запустили ардуину или в первый раз или после пропадания питания..
> Начал выполнятся
> void setup()
> Эти строчки понятно что делают :
> DN = EEPROM.read(DNAdresse);
> firstRun(DN);
> kWhDayAllERROM = EEPROM.get(dAdresse, kWhDayAllERROM);
> kWhNightAllERROM = EEPROM.get(nAdresse,kWhNightAllERROM);
> Вот по этим фунциям, есть вопросы.....
> kWhNightUpdate();
> kWhDayUpdate();
> 
> Допустим рассмотрм void kWhDayUpdate()
> строчки вызывают сомнение :
> uint32_t kWhDay = (vipe[0][3] + vipe[1][3] + vipe[2][3]);
> kWhDayAll=kWhDayAllERROM+kWhDay;
> Массив vipe определен, но он ничем не заполнен, не понятно какие там значения.
> Он начинает заполнятся только при вызове функции readEnergy();, а ее еще не вызывали, она в void loop().
> 
> Что я не понимаю ????

Там же есть комментарий для чего эту функцию пихнул в сетап. Костыль. Нули там.
Не стреляйте в пианиста, он играет как может.

**Comment by conrad66** [comment]
В 22, 23 строчках :
byte TimeAdresseD = 9; // начала адресса куда буду писать время перехода на день
byte TimeAdresseN = 11; // начала адресса куда буду писать время перехода на ночь
а в коде :
EEPROM.put(TarrifAdresseD , int(0));
EEPROM.put(TarrifAdresseN , int(0));
и как раз 
TarrifAdresseD  и TarrifAdresseN ни где не прописаны.

**Comment by dodther** [comment]
"Шарик, ты балбес..." Исправил. :)

**Comment by conrad66** [comment]
И последний для меня не ясный вопрос...
зачем в функциях NightToDay() и DayToNight() происходит обнуления массива vipe ?
Комментарий читал что "функция подсчёта находится ниже", но не понял логики.
Не могли бы вы "разжевать" этот вопрос ? 
Почему функцию подсчёта не поставить ВЫШЕ ? и в каком это месте вообще ? :)

**Comment by dodther** [comment]
Ну вот так получилось.
